# Dual-stream model configuration
# Use SequentialDualStreamModel for time-series training
_target_: src.model.sequential_dual_stream_model.SequentialDualStreamModel

# Architecture dimensions
d_model: 256
num_heads: 8
num_blendshapes: 52

# Audio processing
sample_rate: 16000
target_fps: ${frame_rate}
mel_sequence_length: 256  # Fixed sequence length for frequency-axis processing
stride_frames: 1  # Number of frames to stride between windows for sequential processing

# Mel-spectrogram settings
mel:
  n_fft: 1024
  hop_length: null  # Calculated dynamically from frame_rate
  n_mels: 80
  f_min: 80
  f_max: 8000

# Concatenated 3-window eGeMAPS configuration (PRODUCTION)
emotion_config:
  backend: "opensmile"  # Options: emotion2vec, opensmile, basic
  # OpenSMILE eGeMAPS settings (recommended)
  context_window: 20.0    # 20s context (vs mel's 8.5s)
  update_interval: 0.3    # 300ms updates (real-time)
  feature_set: "eGeMAPSv02"  # eGeMAPSv02, GeMAPS
  feature_level: "Functionals"  # Functionals, LowLevelDescriptors
  device: "cpu"  # OpenSMILE is CPU-only
  cache_dir: null  # Will use default if null
  enable_caching: true
  batch_size: 4
  sample_rate: 16000
  temporal_history_frames: 30  # Legacy parameter (for fallback)
  use_concatenation: true      # Enable 3-window concatenation approach (PRODUCTION)
  window_intervals: [0.0, 0.3, 0.6]  # Time windows: current, -300ms, -600ms
  
  # Fallback to emotion2vec if needed
  emotion2vec_model: "iic/emotion2vec_plus_large"

# Dual-stream attention settings
dual_stream_attention:
  num_mel_channels: 80
  emotion_dim: 256   # Concatenated + compressed dimension (3×88→256)
  emotion_sequence_length: 1  # Single compressed vector (not sequential)
  use_learnable_weights: true
  temperature: 0.5   # Lower temperature for better balance with improved information density
  dropout: 0.1
  # Natural specialization with balanced information density

# Temporal smoothing
temporal_smoothing:
  enable: true
  initial_alpha: 0.8  # Will be learned as parameter

# Model variants for different use cases
variants:
  # High-performance variant with shorter context (faster)
  fast:
    emotion_config:
      context_window: 10.0   # Shorter context
      update_interval: 0.5   # Less frequent updates
      feature_set: "GeMAPS"  # Smaller feature set
    d_model: 128
    num_heads: 4
    mel_sequence_length: 128
  
  # Basic variant (fastest, basic prosodic features)
  basic:
    emotion_config:
      backend: "basic"
      enable_caching: false
    dual_stream_attention:
      emotion_dim: 9  # Basic prosodic features
    d_model: 128
    num_heads: 4
  
  # Long-context variant for maximum context understanding
  long_context:
    emotion_config:
      context_window: 30.0   # 30s context window
      update_interval: 0.2   # More frequent updates
      feature_set: "eGeMAPSv02"
    d_model: 512
    num_heads: 16
    mel_sequence_length: 512
    
  # Emotion2vec fallback (if OpenSMILE fails)
  emotion2vec_fallback:
    emotion_config:
      backend: "emotion2vec"
      model_name: "iic/emotion2vec_plus_large"
      device: "auto"
      batch_size: 2  # Smaller batch due to memory requirements
    dual_stream_attention:
      emotion_dim: 1024

# Monitoring configuration
monitoring:
  enable: true
  log_dir: "logs/emotion_monitor"
  enable_plotting: true
  verbose: false  # Set to true for detailed logs