# Training configuration

# Optimizer
optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-4
  weight_decay: 1e-5
  betas: [0.9, 0.999]

# Learning rate scheduler
lr_scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: 100
  eta_min: 1e-6

# Loss function
loss:
  _target_: src.model.losses.KoeMorphLoss
  mse_weight: 1.0
  l1_weight: 0.1
  perceptual_weight: 0.5

# Training settings
max_epochs: 100
gradient_clip_val: 1.0
accumulate_grad_batches: 1
check_val_every_n_epoch: 5

# Early stopping
early_stopping:
  monitor: "val_loss"
  patience: 15
  mode: "min"

# Model checkpointing
checkpoint:
  monitor: "val_loss"
  mode: "min"
  save_top_k: 3
  save_last: true

# Logging
logging:
  log_every_n_steps: 50
  log_model: false