# Main configuration file for KoeMorph
defaults:
  - data: default  # Use 'data=koemorph_v2' for new data format
  - model: default
  - training: default
  - _self_

# Global settings
seed: 42
device: auto  # auto, cpu, cuda
frame_rate: 60  # 30 or 60 fps (default: 60 for new data)

# Logging
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: true

# Experiment tracking
experiment:
  name: "koemorph_exp"
  tags: []
  notes: ""