# Main configuration file for KoeMorph
defaults:
  - data: default
  - model: default
  - training: default
  - _self_

# Global settings
seed: 42
device: auto  # auto, cpu, cuda
frame_rate: 30  # 30 or 60 fps

# Logging
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: true

# Experiment tracking
experiment:
  name: "koemorph_exp"
  tags: []
  notes: ""